// Log lb hostname
import './_app/lib/polyfills'

// This file loads all the svg's in the assets directory and adds them to the
// svg sprite generated by webpack's svg-sprite-loader. it is disabled in favor
// of using a more accessible approach where JS is not required.
// import './_app/lib/assets'

import * as cookies from './_app/cookies';
import { toggleNodeClass } from './_app/lib/elements'

console.log(cookies.getCookie('SRV'));

const app = document.querySelector('.app')
const menu = document.querySelector('.app-header__navigation')
const menuButton = document.querySelector('.navigation__toggle')

const metaInfo = document.querySelector('.meta__info')
const metaInfoOpen = document.querySelector('.meta__info__toggle')
const metaInfoClose = document.querySelector('.meta__info__close')

const toggleAppFixed = toggleNodeClass(app)('is-fixed')
const toggleMenuActive = toggleNodeClass(menu)('is-active')
const toggleMenuButtonActive = toggleNodeClass(menuButton)('is-active')

menu.classList.add('js-navigation')

window.toggleMenu = function (event) {
  event.preventDefault()

  toggleAppFixed()
  toggleMenuActive()
  toggleMenuButtonActive()
}

const toggleMetaInfoActive = toggleNodeClass(metaInfo)('is-active')

window.openMetaInfo = function (event) {
  event.preventDefault()

  toggleMetaInfoActive()
}

window.closeMetaInfo = function (event) {
  event.preventDefault()

  toggleMetaInfoActive()
}

const calculator = document.querySelector('#calculator'),
      calculatorFields = document.querySelectorAll('.calculator__fields'),
      calculatorFieldWrapper = document.querySelector('.calculator__wrapper')

calculatorFields.forEach(field => {
  field.parentElement.removeChild(field)
})

calculator.onchange = event => {
  let target = event.target,
      value = target.value,
      baseUrl = target.data('base-url');

  calculatorFields.forEach(field => {
    field.parentElement && field.parentElement.removeChild(field)
    if (field.id === `fields-${value}`) calculatorFieldWrapper.appendChild(field)
  })

  target.form.action = baseUrl + value
}
